Deenamma Life, Himalayas loki mingesi Sadhus tho kalisipodam better
Rahu kalam lo puttano, Devudu Prakruthi na meeda paga battayo
nenu korukunna life, nenu korukunna manishi 8 years ga deggara avvaka poga dooram avthademo ani bayametho brathikesthuna
Okate korika manaspurthiga koruthuna, Aa Devudiki papam anipiyadu, na love ki asal nenu evaro telidannatte untadi
em life ra ayya.... True love eanta painful ga untado wait chese vaadike telustadi...!!!
Life lo istapadanina vaallu ardam cheskokapothe unde pain anta inta kaadu...
